// Lints the TypeScript that exists today (the tests) and any future
// src/ modules from the Phase-2 extraction. The legacy inline script in
// index.html is intentionally out of scope until it is modularized.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  // service-worker.js is the legacy hand-written worker (replaced by the generated
  // one in dist builds); the root .mjs files are one-off migration tooling.
  // staff.js is generated by scripts/build-html.mjs (the staff half of app.src.html, split off at build time).
  // functions/api/wallet-pass.js is a generated esbuild bundle (npm run build:wallet) — never lint it.
  // design_handoff_erp_reskin/ is the designer's reference bundle (prototype JS, not shipped code).
  { ignores: ['node_modules/**', 'dist/**', 'test-results/**', 'vendor/**', '**/*.mjs', 'service-worker.js', 'staff.js', 'app.js', 'staff-parts/**', 'functions/api/wallet-pass.js', 'design_handoff_erp_reskin/**'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['tests/**/*.ts', 'src/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  // Extracted app modules (src/js/*.js) run in the single global scope of the inline
  // script after the build-time include, not as ES modules: they reference app globals
  // and are invoked by name from onclick strings ESLint can't see. Lint them for real
  // bugs but give them the browser + app globals and drop the unused-name noise.
  {
    files: ['src/js/**/*.js'],
    languageOptions: {
      globals: {
        document: 'readonly', window: 'readonly', URL: 'readonly', Blob: 'readonly',
        setTimeout: 'readonly', clearTimeout: 'readonly', fetch: 'readonly',
        navigator: 'readonly', location: 'readonly', localStorage: 'readonly',
        // app globals defined in the main inline script (see src/js/app-globals.d.ts)
        S: 'readonly', parseSlots: 'readonly', allSessions: 'readonly', fmt12h: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  // The wallet pass generator source also runs in the Workers runtime (bundled by build:wallet).
  {
    files: ['scripts/wallet/**/*.js'],
    languageOptions: {
      globals: {
        fetch: 'readonly', Response: 'readonly', Request: 'readonly', URL: 'readonly',
        console: 'readonly', crypto: 'readonly', caches: 'readonly', atob: 'readonly', btoa: 'readonly',
        TextEncoder: 'readonly', TextDecoder: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
    },
  },
  // Cloudflare Pages Functions run in the Workers runtime — give them its web globals.
  {
    files: ['functions/**/*.js'],
    languageOptions: {
      globals: {
        fetch: 'readonly', Response: 'readonly', Request: 'readonly', URL: 'readonly',
        console: 'readonly', crypto: 'readonly', caches: 'readonly',
        TextEncoder: 'readonly', TextDecoder: 'readonly',
        atob: 'readonly', btoa: 'readonly', // base64url for the VAPID JWT and push keys
      },
    },
  },
  // Loose ambient declarations for app globals — `any` is intentional here.
  {
    files: ['**/*.d.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
);
