-- ─────────────────────────────────────────────────────────────────────────────
-- Drift check: run this in the SQL editor after ANY migration that touches a
-- function. It prints one row per surprise and nothing when all is well.
--
-- Why it exists: CREATE OR REPLACE FUNCTION replaces the whole definition,
-- attributes included, and pg_proc.prosrc gives you only the BODY. Reproducing
-- a function from prosrc therefore silently drops `security definer`, demoting
-- it to invoker rights. That is how staff lost the ability to add riders on
-- 2026-09-04 (_enforce_booking_price could no longer call the deliberately
-- locked-down _promo_valid), fixed in 20260907120000.
--
-- The expectations below are the INTENT. If a row appears, either the function
-- regressed or the intent changed — decide which, then fix the code or this file.
-- ─────────────────────────────────────────────────────────────────────────────
with expected(fname, want_definer, note) as (values
  -- Definer: reaches past the caller's RLS, or calls a locked-down helper.
  ('_enforce_booking_price', true,  'calls _promo_valid, which anon+authenticated cannot execute'),
  ('_group_ride_cap',        true,  'counts queue_entries rows the caller may not be able to see'),
  ('_solo_ride_cap',         true,  'same: one place per account on an approval session'),
  ('_approval_guard',        true,  'reads sessions/staff beyond the caller'),
  ('_community_booking_gate',true,  'reads customer_tags, staff-only'),
  ('_promo_count',           true,  'writes promo_codes.uses'),
  ('_promo_valid',           true,  'reads promo_codes; revoked from anon+authenticated on purpose'),
  ('_session_fill_status',   true,  'writes sessions.status from a queue_entries trigger'),
  ('_promote_next_waitlist', true,  'promotes across RLS; revoked from anon+authenticated'),
  ('assign_queue_num',       true,  'reads the whole session to pick a number'),
  ('queue_num_update_guard', true,  'same'),
  ('is_staff',               true,  'reads the staff table'),
  ('is_admin',               true,  'reads the staff table'),
  ('_cust_token_ok',         true,  'reads customers.session_token; internal only'),
  ('_oracle_gate',           true,  'writes login_throttle; internal only'),
  ('customer_create_booking',true,  'the whole point: booking without table rights'),
  ('customer_booking_update',true,  'ditto'),
  ('customer_accept_waiver', true,  'stamps the waiver on the caller''s own desk-added bookings; token-checked (20261004173000)'),
  ('customer_addon_stock',   true,  'ditto'),
  ('customer_login',         true,  'reads customers'),
  ('customer_signup',        true,  'writes customers'),
  ('customer_reset',         true,  'reads+writes customers'),
  ('customer_exists',        true,  'reads customers, metered'),
  ('staff_email_for_phone',  true,  'reads staff_phones, metered'),
  ('staff_mark_pwd_changed', true,  'writes staff.must_change_pwd'),
  ('my_bookings',            true,  'reads the caller''s own rows past RLS'),
  ('customer_fix_fields',    true,  'reads customers.fix_fields; the table is staff-only'),
  ('customer_fix_save',      true,  'writes the flagged customers columns, clears the flags, records the history'),
  ('staff_flag_customer',    true,  'sets fix_fields and writes customer_flags, which nobody may write directly'),
  ('_customer_asks',         true,  'reads customers and queue_entries to decide the check-up; internal only'),
  ('customer_oauth_login',   true,  'reads customers by email or apple_email'),
  ('_customer_email_alias',  true,  'trigger: reads other customers rows to keep the two email columns apart'),
  ('list_sessions',          true,  'reads sessions incl. gated ones'),
  ('community_member',       true,  'reads customer_tags'),
  ('_staff_ref_broadcast',   true,  'inserts into realtime.messages whoever made the change'),
  ('customer_ride_news',     true,  'reads and sets the caller''s own ride-news consent; token-checked'),
  ('customer_consents',      true,  'reads and records the caller''s own privacy confirmation and ride-news answer; token-checked'),
  ('customer_deletion_request', true, 'reads, makes or withdraws the caller''s own deletion request; token-checked'),
  ('customer_my_badges',    true,  'reads the caller''s own badges from customer_badges, which is staff-only; token-checked'),
  ('badge_seasons',         true,  'reads the dated badges from badges, which is staff-only; no rider data'),
  ('badge_catalog',         true,  'reads every badge not retired from badges, which is staff-only; no rider data'),
  ('badge_weeks',           true,  'reads the sessions of each week for Perfect Week/Month; the schedule only, no rider data'),
  ('_apply_default_pay',    true,  'reads customers.default_pay for a booking any caller inserts (staff screens, customer_create_booking)'),
  ('_is_vip',                true,  'reads customer_tags (staff-only) for the VIP perk; revoked from anon+authenticated'),
  ('_vip_no_carbon',         true,  'calls _is_vip for a booking any caller inserts or changes'),
  ('staff_community_ask_changes', true, 'writes community_applications (staff-only); is_staff()-gated'),
  ('community_fix_get',      true,  'reads one application by its change token for the applicant; anon'),
  ('community_fix_submit',   true,  'writes the asked fields of one application by its token; anon, _ip_gate-metered'),
  ('_community_app_to_account', true, 'writes an application''s answers onto its account; no client may execute it'),
  ('_learn_app_to_account', true, 'writes a learn-to-ride sign-up''s answers about the person onto its account; no client may execute it'),
  ('staff_learn_ask_changes', true, 'writes learn_applications (staff-only); is_staff()-gated'),
  ('learn_fix_get',          true,  'reads one learn-to-ride sign-up by its change token for the applicant; anon'),
  ('learn_fix_submit',       true,  'writes the asked fields of one learn-to-ride sign-up by its token; anon, _ip_gate-metered'),
  ('staff_set_customer_temp_password', true, 'writes customers.password_hash + must_change_pwd; is_staff()-gated'),
  ('customer_community_apply', true, 'writes community_applications (staff-only) for the signed-in applicant; token-checked, _ip_gate-metered'),
  ('customer_community_me',  true,  'reads the caller''s own account, application and tags for the form; token-checked'),
  ('customer_learn_apply',   true,  'the learn-to-ride sign-up from the signed-in account (learn_apply behind it); token-checked'),
  -- The 2026-10-03 review fixes (20261004100000); vendor_logout is listed with the vendor portal's
  ('customer_change_password',  true,  'writes customers.password_hash, login_throttle and customer_owner_pwd; token-checked'),
  ('customer_purchases',        true,  'reads the rider''s own cashier_sales, which customers cannot read; token-checked'),
  ('customer_push_subscribe',   true,  'writes push_subscriptions for the signed-in rider; token-checked, known push services only'),
  ('staff_my_settings',         true,  'writes the caller''s own staff row, auth metadata and team-list name; staff only'),
  ('_safe_date',                false, 'pure date parse'),
  ('_badge_rule_ok',        false, 'pure shape test of a badge rule, for the check constraint'),
  -- Invoker on purpose: pure logic, no privileged read.
  ('_name_chars_ok',         false, 'pure regex test, no read'),
  ('_name_parts_ok',         false, 'pure word-length test, no read'),
  ('_customer_name_ok',      false, 'name-rule trigger; is_staff() does its own privileged read'),
  ('_capacity_guard',        false, 'counts rows already visible in its calling context'),
  ('_comm_no_carbon',        false, 'inspects NEW only'),
  ('_wl_num_assign',         false, 'inspects NEW + same-session rows'),
  ('_ctag_active',           false, 'pure date comparison'),
  ('_cust_pwd_ok',           false, 'pure hash comparison'),
  -- Rider registration (the form at micromobility.sa/petromin)
  ('rider_register',         true,  'writes rider_registrations for anon; reads queue_entries and customers to match'),
  ('rider_edit',             true,  'same, for the rider''s own row'),
  ('rider_party_add',        true,  'inserts companions for staff; the table grants no insert'),
  ('rider_sessions',         true,  'reads sessions for anon'),
  ('_rider_gate',            true,  'writes login_throttle; internal only'),
  ('_rider_session_open',    false, 'pure status check on the row it is handed'),
  ('_session_window',        false, 'pure time arithmetic on the row it is handed'),
  ('_rider_price',           false, 'pure price table'),
  ('_rider_registration_guard', false, 'inspects NEW only; calls _rider_price at return time'),
  -- The employee fare (20260921190000)
  ('_employee_fare',         false, 'pure price table'),
  ('_booking_fare',          false, 'reads rider_registrations, but only ever runs inside the definer triggers; revoked from anon+authenticated'),
  ('_rider_link_reprice',    true,  'trigger: reprices the linked queue_entries row whoever made the link, anon form included'),
  -- The website content store (20260924150000)
  ('_site_content_log',     true,  'writes site_content_history, which has no write policy for anyone'),
  ('_site_content_stamp',   false, 'sets updated_at/updated_by on NEW only'),
  -- Workshop service requests (20260924160000)
  ('workshop_request',      true,  'the website form writes workshop_jobs, which anon cannot touch; metered'),
  ('workshop_track',        true,  'reads one job for its reference + phone; metered'),
  ('_workshop_log',         true,  'writes workshop_job_events, which has no write policy for anyone'),
  ('_workshop_stamp',       false, 'sets updated_at/updated_by on NEW only'),
  -- Messages from the website (20260924170000)
  ('site_message_send',     true,  'the business, help and job application forms write site_messages, which anon cannot touch; metered'),
  ('_site_messages_stamp',  false, 'sets updated_at/updated_by on NEW only'),
  -- Ambassadors and the Club (20260924180000)
  ('ambassador_apply',      true,  'the website form writes ambassadors, which anon cannot touch; metered'),
  ('ambassador_portal',     true,  'one ambassador''s card for their code + mobile; metered'),
  ('ambassador_redeem',     true,  'writes ambassador_redemptions for a code + mobile; metered'),
  ('ambassador_board',      true,  'the season''s top five: first names and codes only; metered'),
  ('club_card',             true,  'one member''s card for their email + mobile; reads customers and bookings; metered'),
  ('club_rides',            true,  'upcoming open community rides: titles, days and times only; metered'),
  ('staff_ambassador_set',  true,  'approves/pauses an ambassador and switches their promo code; checks is_staff() itself'),
  ('staff_ambassador_stats',true,  'every ambassador''s numbers; checks is_staff() itself'),
  ('_amb_events',           true,  'reads bookings and workshop jobs for a code; internal only'),
  ('_amb_summary',          true,  'an ambassador''s totals; internal only'),
  ('_amb_redeem_items',     true,  'reads the rewards list from site_content; internal only'),
  ('_site_num',             true,  'reads one number from site_content; internal only'),
  ('_amb_discount_sync',    true,  'reprices the ambassador promo codes when the discount is saved'),
  ('_amb_stamp',            false, 'sets updated_at/updated_by on NEW only'),
  ('_try_ts',               false, 'parses a text time; pure'),
  -- Staff devices' delta sync (20260924230000)
  ('staff_sync',            false, 'invoker on purpose: the tables'' own staff policies decide what it returns, and it refuses non-staff itself'),
  ('staff_operator_list',    true,  'reads team_members.pin_hash, which no client can select'),
  ('staff_set_operator_pin', true,  'writes team_members.pin_hash; admins only'),
  ('staff_check_operator_pin',true, 'reads the hash, writes login_throttle'),
  ('staff_team_list',        true,  'reads staff and auth.users; admins only'),
  ('staff_set_access',       true,  'writes staff rows, which no client can update; admins only'),
  ('_sync_touch',           false, 'sets updated_at on NEW only'),
  ('_sync_tombstone',       true,  'writes sync_deletions, which the deleting role cannot'),
  -- The 2026-09-22 review fixes (20260922120100 … 124000)
  ('promo_lookup',           true,  'answers one code for the booking form; promo_codes is staff-only'),
  ('_ip_gate',               true,  'writes login_throttle for every per-network meter; internal only'),
  ('staff_inventory_costs',  true,  'reads inventory.cost, which anon and authenticated cannot'),
  ('_addons_held_sync',      true,  'trigger: fires on staff writes, whatever the caller may execute'),
  ('_client_ip',             false, 'reads a request header, nothing else'),
  ('_fare_now',              false, 'reads sessions/ride_prices, only ever inside the definer trigger and RPC; revoked'),
  ('_promo_fare',            false, 'pure arithmetic on the code row it is handed'),
  ('_addon_map',             false, 'pure JSON reshaping'),
  ('_addons_ok',             false, 'pure shape test, used by a CHECK constraint'),
  ('_socials_ok',            false, 'pure shape test, used by a CHECK constraint'),
  ('_type_ok',               false, 'pure list test, used by CHECK constraints'),
  ('_ymd_ok',                false, 'pure date test'),
  ('_session_has_room',      false, 'counts queue_entries, only ever inside customer_booking_update; revoked'),
  ('_session_fill_recount',  false, 'the fill rule for one session, only ever inside the definer trigger; revoked'),
  -- One-step account delete and the narrow profile saves (20260922150000)
  ('staff_delete_customer',  true,  'unlinks bookings and sales, deletes tags, push rows and the account in one go; admin only'),
  ('customer_set_height',    true,  'writes the caller''s own height; token-checked'),
  ('customer_set_birth_nat', true,  'writes the caller''s own birth date and nationality; token-checked'),
  -- The 2026-09-25 review fixes (20260925140000)
  ('customer_profile',       true,  'reads the caller''s own customers row, the perk and hidden types included; token-checked'),
  ('customer_update_profile',true,  'writes the caller''s own customers row; token-checked, a new phone or email metered'),
  ('customer_oauth_signup',  true,  'writes customers for a Google/Apple sign-in; metered'),
  ('staff_set_customer_password', true, 'writes customers.password_hash, which no client can select; staff only'),
  ('_error_log_gate',        true,  'trigger: meters error_log inserts per network through _ip_gate'),
  -- The 2026-09-27 feature round (20260928120000 … 20260928170000)
  ('staff_merge_customers',  true,  'moves every row of one account onto another across twelve tables; admins only'),
  ('staff_unmerge_customers',true,  'puts a merge back within thirty days; admins only'),
  ('_booking_window_guard',  false, 'trigger: reads site_content, which everyone may; is_staff() does its own privileged read'),
  ('staff_live_position',    true,  'writes live_positions, which no client can write; staff only'),
  ('staff_live_stop',        true,  'deletes from live_positions; staff only'),
  ('live_positions_for',     true,  'reads live_positions for a rider with a booking on the ride; token-checked'),
  ('member_area',            true,  'one member''s own area: reads customers, bookings, tags and site_content; token-checked'),
  ('ambassador_mine',        true,  'the signed-in account''s own ambassador card; token-checked'),
  -- Staff guardrails (20260928200000)
  ('_audit_row',             true,  'trigger: writes audit_log, which has no write policy for anyone'),
  ('staff_pin_approve',      true,  'reads team_members.pin_hash through staff_check_operator_pin, writes pin_approvals; staff only'),
  ('_pin_ok',                true,  'reads team_members.pin_hash and pin_approvals, which no client can select; internal only'),
  ('staff_void_receipt',     true,  'marks a receipt''s rows voided whoever the staffer is; PIN-checked'),
  ('staff_refund_receipt',   true,  'marks a receipt''s rows refunded; PIN-checked'),
  ('staff_set_price',        true,  'writes queue_entries.price; PIN-checked'),
  ('staff_delete_session',   true,  'sets a ride deleted past the admin-only column trigger; admins only, PIN-checked'),
  ('staff_delete_bike',      true,  'deletes a bike row; admins only, PIN-checked'),
  ('_sessions_admin_cols',   false, 'inspects NEW/OLD only; is_admin() does its own privileged read'),
  ('_bikes_admin_cols',      false, 'same, for rental_price'),
  ('_customers_admin_cols',  false, 'same, for default_pay and hidden_types'),
  ('_close_assignments_on_reassign', true, 'trigger: closes bike_assignments rows whoever changed the booking, like _close_assignments_on_leave_active'),
  ('_bike_ids',              false, 'pure parse of assigned_bike_id, no read'),
  ('_queue_stamps',          false, 'sets the four timestamps on NEW only'),
  -- Learn to ride (20260928210000, 20260928230000)
  ('learn_apply',            true,  'writes learn_applications; only customer_learn_apply calls it since 20261004100000 (revoked from anon/authenticated)'),
  ('staff_learn_schedule',   true,  'finds or makes the account and records the lesson; checks is_staff() itself'),
  ('staff_learn_new_password', true, 'writes customers.password_hash, which no client can select; staff only'),
  ('staff_learn_decide',     true,  'moves a sign-up between its states; checks is_staff() itself'),
  ('_learn_heard_to_account',true,  'trigger: writes customers.heard_from whoever set the sign-up''s account; internal only'),
  -- Workplace and the account page's "about" fields (20260929110000)
  ('community_apply',        true,  'writes community_applications; revoked from anon/authenticated since 20261004100000 (customer_community_apply is the form''s way in)'),
  ('staff_community_approve',true,  'finds or makes the account; checks is_staff() itself'),
  ('customer_about',         true,  'reads the signed-in rider''s own customers row; token-checked'),
  ('customer_set_about',     true,  'writes the signed-in rider''s own customers row; token-checked'),
  -- Google / Apple marks beside the email (20260929140000)
  ('_sign_in_methods',       true,  'reads auth.identities and customers.password_hash, which no client may; internal only'),
  ('staff_sign_in_methods',  true,  'every account''s sign-in methods; checks is_staff() itself'),
  -- Staff reset an account's sign-in wait (20260930110000)
  ('_sign_in_lock_rows',     true,  'reads login_throttle (RLS on, no policy) and audit_log; internal only'),
  ('staff_sign_in_lock',     true,  'one account''s failed tries and lock; checks is_staff() itself'),
  ('staff_clear_sign_in_lock', true, 'deletes one account''s login_throttle rows; is_staff()-gated'),
  -- One number on several accounts, the first holder signs in with it (20260930180000)
  ('_phone_main',            true,  'reads every account on a number; internal only (customer_login, staff_phone_accounts)'),
  ('staff_phone_accounts',   true,  'the accounts on a number and which signs in; checks is_staff() itself'),
  ('_vendor_today',             false, 'vendors: today in Riyadh; pure'),
  ('_vendor_login_key',         false, 'pure normalising of a venue login'),
  ('_vendor_pattern_days',      false, 'pure date arithmetic for a monthly pattern'),
  ('_vendor_user',              true,  'checks the venue session through _vendor_auth (vendor_sessions, no client grant); internal only'),
  ('_vendor_audit_row',         true,  'trigger: writes vendor_audit, which no client can write'),
  ('_vendor_sync_day',          true,  'writes sessions.breakfast_* from a venue or staff action; internal only'),
  ('_vendor_session_fill',      true,  'trigger: reads vendor_bookings/vendor_venues whoever makes the ride'),
  ('_vendor_check',             true,  'reads every venue''s bookings to judge a date; internal only'),
  ('vendor_login',              true,  'reads vendor_users.password_hash, writes login_throttle; anon, metered'),
  ('vendor_set_password',       true,  'writes vendor_users.password_hash; token-checked'),
  ('vendor_me',                 true,  'the signed-in venue, its tier and patterns; token-checked'),
  ('vendor_calendar',           true,  'dates, own requests, taken flags, rider count; token-checked'),
  ('vendor_preview',            true,  'verdict per date for a request; token-checked'),
  ('vendor_request',            true,  'writes vendor_bookings/vendor_series, which no client can write; token-checked'),
  ('vendor_cancel',             true,  'cancels the venue''s own bookings; token-checked'),
  ('vendor_profile_save',       true,  'writes the venue''s own profile fields; token-checked'),
  ('staff_vendor_venue_save',   true,  'writes vendor_venues; checks is_staff() itself'),
  ('staff_vendor_user_add',     true,  'writes vendor_users with a temporary password; checks is_staff() itself'),
  ('staff_vendor_user_reset',   true,  'writes vendor_users.password_hash; checks is_staff() itself'),
  ('staff_vendor_user_active',  true,  'switches a venue login; checks is_staff() itself'),
  ('staff_vendor_decide',       true,  'confirms/declines/cancels a booking and sets the ride breakfast; checks is_staff() itself'),
  ('staff_vendor_date_set',     true,  'opens/closes a date and cancels its bookings; checks is_staff() itself'),
  ('staff_vendor_dates_open',   true,  'opens a range of dates; checks is_staff() itself'),
  ('staff_vendor_tier_save',    true,  'writes vendor_tiers; checks is_admin() itself'),
  ('vendor_feedback_save',      true,  'writes vendor_feedback, which no client can write; token-checked'),
  ('staff_vendor_share_ratings', true, 'reads riders'' breakfast ratings (queue_entries) and writes vendor_shared_ratings; checks is_staff() itself'),
  ('staff_vendor_unshare_ratings', true, 'deletes one vendor_shared_ratings row; checks is_staff() itself'),
  ('vendor_shared_ratings_mine', true, 'the signed-in vendor''s own shared breakfast ratings, no rider names; token-checked'),
  -- Staff security, 2026-10-04 (20261004120000)
  ('_pin_ok_strict',         true,  'reads team_members.pin_hash through _pin_ok; internal only'),
  ('staff_purge_session',    true,  'deletes an empty deleted session past RLS; admins only, PIN-checked'),
  ('staff_checkin',          true,  'claims bikes, writes bike_assignments and the booking''s payment in one go; checks is_staff() itself'),
  ('_addons_price_snapshot', true,  'trigger: reads inventory prices and is_staff() for a booking any caller writes'),
  -- 20261004130000 (vendor portal hardening): sessions by hash, roles, password policy, the gate
  ('_vendor_auth',              true,  'reads vendor_sessions (no client grant) by token hash, writes last_seen; internal only'),
  ('_vendor_role',              false, 'pure: refuses a role not in the list'),
  ('_vendor_phone',             false, 'pure normalising of a contact phone to E.164'),
  ('_vendor_pwd_problem',       true,  'reads vendor_venues names to refuse a personal password; internal only'),
  ('_vendor_ride_time',         true,  'reads the Saturday ride''s bike_slots whoever asks; internal only'),
  ('_vendor_riders',            true,  'counts queue_entries rows the venue cannot see; internal only'),
  ('_vendor_session_bf_guard',  true,  'trigger: clears sessions.breakfast_name_ar/offer when staff retype the stop'),
  ('vendor_logout',             true,  'deletes the caller''s own vendor_sessions row by token hash; anon'),
  ('vendor_logout_others',      true,  'deletes the login''s other vendor_sessions rows; token-checked'),
  ('vendor_team',               true,  'the venue''s logins for its owners, no secrets; token-checked'),
  ('_cact_row',                 true,  'trigger: writes customer_activity, which no client can write; reads sessions/customers/ambassadors'),
  ('_cact_add',                 true,  'writes customer_activity for _cact_row; no client may execute it'),
  -- The 2026-10-05 audit (20261005210000 … 20261005210200)
  ('_waiver_min',               false, 'pure: the current minimum waiver version of each kind'),
  ('_waiver_outdated',          false, 'pure comparison of a version with _waiver_min'),
  ('_house_taken',              false, 'reads queue_entries/customers, only ever inside the definer triggers and RPCs; revoked'),
  ('_session_capacity_promote', true,  'trigger: recounts a session and promotes its waitlist whoever raised the capacity or reopened it'),
  ('customer_waitlist_ranks',   true,  'reads the session''s waitlist for the caller''s own rows; token-checked'),
  ('staff_rider_party_move',    true,  'moves a Petromin party, its night counter and its bookings; checks is_staff() itself')
)
select e.fname,
       case when p.oid is null then 'MISSING FROM DATABASE'
            else 'security definer is ' || p.prosecdef || ', expected ' || e.want_definer end as problem,
       e.note
from expected e
left join pg_proc p on p.proname = e.fname
     and p.pronamespace = 'public'::regnamespace
where p.oid is null or p.prosecdef <> e.want_definer;
