#!/usr/bin/env node
// Generated staging data (2026-09-28): riders, sessions, bookings, bikes, tags and staff options that
// never existed, so a staging project can be filled without a byte of production's personal data
// (names, phones, birth dates and nationalities are under the privacy notice; a copy of them in a
// less-guarded project is a data-protection exposure). Deterministic: the same seed gives the same
// SQL, so two people looking at staging see the same riders.
//
//   node scripts/seed-staging.mjs > /tmp/seed.sql        # then run it in the STAGING project's SQL editor
//   node scripts/seed-staging.mjs --riders 500 --weeks 8 --seed 7
//
// Apply every migration first (supabase db push against the staging project); the seed only writes
// rows. Never run this against production: the first statement refuses when a real staff row exists.
const args = Object.fromEntries(process.argv.slice(2).map((a, i, all) => a.startsWith('--') ? [a.slice(2), all[i + 1]] : []).filter((x) => x.length));
const N_RIDERS = Math.max(20, Math.min(5000, parseInt(args.riders || '300', 10) || 300));
const WEEKS = Math.max(1, Math.min(52, parseInt(args.weeks || '10', 10) || 10));
let seed = (parseInt(args.seed || '2026', 10) || 2026) >>> 0;
const rnd = () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; };
const pick = (a) => a[Math.floor(rnd() * a.length)];
const int = (lo, hi) => lo + Math.floor(rnd() * (hi - lo + 1));
const q = (v) => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const FIRST = ['Amal', 'Badr', 'Cala', 'Dina', 'Eid', 'Fadi', 'Ghada', 'Hala', 'Ibrahim', 'Jana', 'Khalid', 'Lama', 'Majed', 'Nora', 'Omar', 'Rana', 'Saad', 'Talal', 'Wafa', 'Yara', 'Ziad', 'Reem', 'Faisal', 'Hind', 'Sultan', 'Layla', 'Nawaf', 'Sara', 'Tariq', 'Maha'];
const LAST = ['Saleh', 'Ali', 'Hassan', 'Omar', 'Khan', 'Rahman', 'Yousef', 'Ahmed', 'Malik', 'Nasser', 'Qasim', 'Zahra', 'Farid', 'Habib', 'Idris', 'Jaber', 'Karim', 'Latif', 'Mansour', 'Najjar'];
const TYPES = ['Road', 'Hybrid', 'Hybrid', 'Mountain', 'Any', 'Any', 'Kids'];
const SIZES = ['XS', 'S', 'M', 'L', 'XL'];
const NAT = ['Saudi Arabia', 'Egypt', 'Pakistan', 'India', 'Philippines', 'Jordan', 'Sudan', 'Bangladesh', 'Nepal', 'Yemen'];
const day = (offset) => { const d = new Date(Date.UTC(2026, 8, 28 + offset)); return d.toISOString().slice(0, 10); };
const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const dayName = (iso) => DAYS[new Date(iso + 'T12:00:00Z').getUTCDay()];
const out = [];
out.push(`-- staging seed: ${N_RIDERS} riders, ${WEEKS} weeks, seed ${args.seed || 2026}. Generated by scripts/seed-staging.mjs; never for production.`);
out.push(`do $$ begin if exists (select 1 from public.staff where user_id in (select id from auth.users where email like '%@micromobility.sa')) then raise exception 'This looks like production (staff accounts on the company domain): the seed refuses to run here.'; end if; end $$;`);
out.push(`begin;`);
// tags
out.push(`insert into public.tags (id, slug, name, color, description, auto_grant, locked, created_at) values ('tag_saturday','saturday','Community','#0c7a3d','Community member',false,true,${Date.now()}) on conflict (id) do nothing;`);
// bikes: 40, numbered, types and sizes
const bikes = [];
for (let n = 1; n <= 40; n++) {
  const type = n <= 14 ? 'Hybrid' : n <= 26 ? 'Road' : n <= 34 ? 'Mountain' : 'Kids';
  const size = type === 'Kids' ? pick(['XS', 'S']) : pick(SIZES);
  bikes.push({ id: `stg-bike-${n}`, n, type, size });
  out.push(`insert into public.bikes (id, name, size, type, colors, color_names, status, brand, model, frame_type, bike_number, in_service_date, serial_number, created_at) values (${q(`stg-bike-${n}`)}, ${q(`${type} ${size} ${String(n).padStart(3, '0')}`)}, ${q(size)}, ${q(type)}, '["#03ff89"]'::jsonb, '["Green"]'::jsonb, 'available', 'Alvas', ${q(type === 'Road' ? 'Climax' : type === 'Hybrid' ? 'Cross 21S' : type === 'Mountain' ? 'Strom M50' : 'Beta')}, 'Aluminum', ${n}, '2026-10-01', ${q(`STG-SN-${1000 + n}`)}, now()) on conflict (id) do nothing;`);
}
// riders
const riders = [];
for (let i = 1; i <= N_RIDERS; i++) {
  const first = pick(FIRST), last = pick(LAST);
  const id = `stg-c-${String(i).padStart(4, '0')}`;
  const phone = `+96650${String(1000000 + i).slice(-7)}`;
  const born = 1970 + int(0, 46);
  riders.push({ id, name: `${first} ${last}`, phone, member: rnd() < 0.25, type: pick(TYPES), height: int(150, 195) });
  out.push(`insert into public.customers (id, name, email, phone, password_hash, created_at, height, type_preference, gender, birth_date, country, city, nationality, privacy_version, privacy_at) values (${q(id)}, ${q(`${first} ${last}`)}, ${q(`${first.toLowerCase()}.${last.toLowerCase()}.${i}@example.com`)}, ${q(phone)}, 'oauth:google', ${q(new Date(Date.UTC(2026, int(0, 8), int(1, 28))).toISOString())}, ${riders[i - 1].height}, ${q(riders[i - 1].type)}, ${q(pick(['male', 'female']))}, ${q(`${born}-${String(int(1, 12)).padStart(2, '0')}-${String(int(1, 28)).padStart(2, '0')}`)}, 'Saudi Arabia', 'Jeddah', ${q(pick(NAT))}, 'v2026-09-25', now()) on conflict (id) do nothing;`);
  if (riders[i - 1].member) out.push(`insert into public.customer_tags (customer_id, tag_id, added_by, added_at) values (${q(id)}, 'tag_saturday', 'seed', ${Date.now() - int(1, 200) * 86400000}) on conflict do nothing;`);
}
// sessions: past and future weeks; a circuit night Mon/Wed/Thu, a Saturday ride, a monthly event
const sessions = [];
for (let w = -Math.floor(WEEKS / 2); w < Math.ceil(WEEKS / 2); w++) {
  for (const dow of [1, 3, 4]) {
    const iso = day(w * 7 + dow); const past = iso < day(0);
    sessions.push({ id: iso, date: iso, kind: 'jcc', past });
    out.push(`insert into public.sessions (id, day, session_date, capacity, status, created_at, bike_slots, location) values (${q(iso)}, ${q(dayName(iso))}, ${q(iso)}, 40, ${q(past ? 'closed' : 'open')}, now()::text, '{"_time":"21:00 - 23:00","_total":40}', 'JCC') on conflict (id) do nothing;`);
  }
  const sat = day(w * 7 + 6); const satPast = sat < day(0);
  sessions.push({ id: sat, date: sat, kind: 'saturday', past: satPast });
  out.push(`insert into public.sessions (id, day, session_date, capacity, status, created_at, bike_slots, event_kind, ride_kind, needs_approval, hide_queue, spots, paid_ride) values (${q(sat)}, 'Saturday', ${q(sat)}, 25, ${q(satPast ? 'closed' : 'open')}, now()::text, '{"_time":"06:30 - 07:00"}', 'community', 'saturday', true, true, 25, false) on conflict (id) do nothing;`);
  if (w % 4 === 1) {
    const ev = day(w * 7 + 2); const evPast = ev < day(0);
    out.push(`insert into public.sessions (id, day, session_date, capacity, status, created_at, bike_slots, event_kind, ride_kind, needs_approval, hide_queue, spots, paid_ride, open_to_all, title, description, price) values (${q(ev + '-ev')}, ${q(dayName(ev))}, ${q(ev)}, 30, ${q(evPast ? 'closed' : 'open')}, now()::text, '{"_time":"19:00 - 21:00"}', 'community', 'event', false, true, 30, true, true, 'Bike maintenance class', 'Two hours on brakes, gears and flats.', 40) on conflict (id) do nothing;`);
  }
}
// bookings: past nights done and rated, future nights waiting
let qn = 0;
for (const s of sessions) {
  const n = s.kind === 'jcc' ? int(18, 40) : int(8, 22);
  const used = new Set();
  for (let k = 1; k <= n; k++) {
    let r = pick(riders); if (used.has(r.id)) continue; used.add(r.id);
    if (s.kind === 'saturday' && !r.member) continue;
    qn++;
    const id = `stg-q-${String(qn).padStart(5, '0')}`;
    const status = s.past ? (rnd() < 0.9 ? 'done' : rnd() < 0.5 ? 'noshow' : 'cancelled') : (rnd() < 0.92 ? 'waiting' : 'cancelled');
    const bike = s.kind === 'jcc' && status === 'done' ? pick(bikes) : null;
    const rated = status === 'done' && rnd() < 0.6;
    const price = s.kind === 'jcc' ? (r.type === 'Road' ? 75 : 50) : 0;
    out.push(`insert into public.queue_entries (id, name, email, phone, size, type_preference, paid, price, assigned_bike_id, session_id, session_day, session_date, queue_num, status, registered_at, walk_in, customer_id, height, rating_bike, rating_exp, feedback, checked_in_at, checked_out_at, approval) values (${q(id)}, ${q(r.name)}, null, ${q(r.phone)}, ${q(SIZES[Math.min(4, Math.max(0, Math.floor((r.height - 150) / 10)))])}, ${q(s.kind === 'saturday' ? 'Own' : r.type)}, ${status === 'done' || (s.kind === 'jcc' && rnd() < 0.3)}, ${price}, ${q(bike ? bike.id : null)}, ${q(s.id)}, ${q(dayName(s.date))}, ${q(s.date)}, ${k}, ${q(status)}, ${q(new Date(new Date(s.date).getTime() - int(1, 6) * 86400000).toISOString())}, false, ${q(r.id)}, ${r.height}, ${rated && bike ? int(5, 10) : 'null'}, ${rated ? int(4, 10) : 'null'}, ${rated && rnd() < 0.3 ? q(pick(['Great night', 'Saddle was low', 'Loved the pace', 'More lights please'])) : 'null'}, ${status === 'done' ? q(s.date + 'T18:05:00Z') : 'null'}, ${status === 'done' ? q(s.date + 'T20:10:00Z') : 'null'}, ${q(s.kind === 'saturday' ? 'approved' : null)}) on conflict (id) do nothing;`);
  }
}
out.push(`insert into public.site_content (key, value, updated_by) values ('site.coming_soon', 'true'::jsonb, 'seed') on conflict (key) do nothing;`);
out.push(`insert into public.site_content (key, value, updated_by) values ('booking.window', '{"days": 14, "at": "20:00"}'::jsonb, 'seed') on conflict (key) do nothing;`);
out.push(`insert into public.staff_options (key, items) values ('service_every', '[40]'::jsonb) on conflict (key) do nothing;`);
out.push(`commit;`);
process.stdout.write(out.join('\n') + '\n');
